export const select = document.querySelector("#from");
export const selectTo = document.querySelector("#to");
export const input = document.querySelector(".amount input");
export const line1 = document.querySelector(".cur2-text h2");
export const line2 = document.querySelector(".cur1-text");
export const line3 = document.querySelector(".rate1");
export const line4 = document.querySelector(".rate2");
export const exchangeIcon = document.querySelector(".switch");
export const curContainer = document.querySelector(".cur-container");
